version: '2'
services:
  api:
    container_name: app
    build: ./app/
    links:
      - db
    environment:
      - DATABASE_URL=postgres://user:123456@db:5432/user
    ports:
      - "3000:3000"
    volumes:
      - ./app:/web
    command: bash -c "npm install && npm start"
  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456